### ISSUE TITLE
Add tasks to wait until the URL is reachable

### ISSUE THREAD

**Issue by kastl-ars** [robertdebock/ansible-role-artifactory#13]
Hi Robert,

# Proposed feature

The last task in the role is to start the `artifactory.service`. As this can take some time, it would be nice to have a task after that checking / waiting for the Artifactory URL to be reachable.

Here is an example [from one of my setups](https://github.com/johanneskastl/openbao_vagrant_libvirt_ansible/blob/main/ansible/playbook-server-configure_and_start_openbao_server.yml#L106C1-L112C16):

```
    - name: 'Wait until the OpenBao URL is reachable'
      ansible.builtin.uri:
        url: "http://{{ hostvars['openbao']['ansible_default_ipv4']['address'] }}:8200"
      register: result
      until: "result.status == 200"
      retries: 11
      delay: 10
```

Also, adding a `debug` task that outputs the actual IP and Port where Artifactory is reachable is also nice to have.

Kind Regards,
Johannes
