### ISSUE TITLE
Do not restart the service, if it has just been started (for the first time)

### ISSUE THREAD

**Issue by kastl-ars** [robertdebock/ansible-role-artifactory#14]
# Proposed feature
The service takes loooong to get start. And it failed on my multiple times during the restart. 

For some of my vagrant test setups I have added a `when`-condition to the restart, that only restarts the service, if it was already running, i.e. it was not just started for the first time.

[Example](https://github.com/johanneskastl/distribution-container-registry_vagrant_libvirt_ansible/blob/main/ansible/playbook-all_nodes-configure_and_start_distribution-container-registry.yml) (from a playbook, not a role, but you get the idea):

```
  handlers:

    - name: 'Restart the registry service'
      ansible.builtin.service:
        name: 'registry'
        state: 'restarted'
      when:
        - 'not distribution_container_registry_service_started.changed | bool'
[...]
  tasks:

    - name: 'Start the registry service'
      ansible.builtin.service:
        name: 'registry'
        state: 'started'
      register: distribution_container_registry_service_started
```

## Rationale

Avoid unnecessary restarts of the service

## Additional context

This should be pretty fail-safe. If the service was stopped and a configuration file changes, it should get started. Only thing is, it might be better to separate starting and enabling into two separate tasks, to not skip the restart if the service was already running but not enabled.

I can come up with a PR, if you like.
