### ISSUE TITLE
document the dependency on robertdebock.service

### ISSUE THREAD

**Issue by weakcamel** [robertdebock/ansible-role-artifactory#4]
**Describe the bug**

The artifactory role is dependent on robertdebock.service role, however this is not documented in the README nor role's metadata (dependencies list).

**Playbook**
Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
# requirements.yml
- src: robertdebock.bootstrap
  version: 4.0.3
- src: robertdebock.java
  version: 2.4.1
- src: robertdebock.artifactory
  version: 3.0.0
- src: robertdebock.core_dependencies
```

```yaml
---
- name: Deploy Artifactory
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Bootstrap OS
      import_role:
        name: robertdebock.bootstrap
    - name: Install Java
      import_role:
        name: robertdebock.java
    - name: Install Artifactory
      import_role:
          name: robertdebock.artifactory
  
```

**Output**
Show at least the error, possible related output, maybe just all the output.

```
ERROR! the role 'robertdebock.service' was not found in /Users/weakcamel/git/jfrog-automation/ansible/roles:/Users/weakcamel/git/jfrog-automation/ansible/galaxy-roles:/Users/weakcamel/git/jfrog-automation/ansible/roles:/Users/weakcamel/git/jfrog-automation/ansible

The error appears to be in '/Users/weakcamel/git/jfrog-automation/ansible/galaxy-roles/robertdebock.artifactory/tasks/main.yml': line 55, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  import_role:
    name: robertdebock.service
          ^ here
```

**Expected behavior**

Dependencies documented in README.md and/or dependencies section in `meta/main.yml`

**Environment**
- Control node OS: Darwin 19.0.0
- Control node Ansible version: ansible 2.9.2
- Managed node OS: Ubuntu bionic (18.04)
