### ISSUE TITLE
Creating a wrong artifactory_file_store_dir

### ISSUE THREAD

**Issue by weakcamel** [robertdebock/ansible-role-artifactory#6]
**Describe the bug**

Instead of using the interpolated value of the `artifactory_file_store_dir` variable, the role uses literal string `artifactory_file_store_dir`.

The bug is in this line:

https://github.com/robertdebock/ansible-role-artifactory/blob/105bc568a856c766e9e3b690d2671c7dcba44755/tasks/main.yml#L43

**Playbook**

```yaml
    ...
    - name: OS bootstrap verification
      import_role:
        name: robertdebock.bootstrap
    - name: Install Java
      import_role:
        name: robertdebock.java
    - name: Install Artifactory
      import_role:
        name: robertdebock.artifactory
```

**Output**

Output from the installation is:

```
$ ls -al
total 36
drwxr-xr-x 5 ubuntu ubuntu 4096 Jan  2 16:17 .
drwxr-xr-x 4 root   root   4096 Jan  2 16:13 ..
drwxr-xr-x 2 root   root   4096 Jan  2 16:14 artifactory_file_store_dir
-rw------- 1 ubuntu ubuntu   59 Jan  2 16:55 .bash_history
-rw-r--r-- 1 ubuntu ubuntu  220 Aug 31  2015 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu 3771 Aug 31  2015 .bashrc
drwx------ 2 ubuntu ubuntu 4096 Jan  2 16:10 .cache
-rw-r--r-- 1 ubuntu ubuntu  655 Jul 12 19:26 .profile
drwx------ 2 ubuntu ubuntu 4096 Jan  2 16:08 .ssh
-rw-r--r-- 1 ubuntu ubuntu    0 Jan  2 16:10 .sudo_as_admin_successful
```

**Expected behavior**

Filestore directory actually created as configured instead of literal path `artifactory_file_store_dir`

**Environment**
- Control node OS: Darwin 19.0.0
- Control node Ansible version: ansible 2.9.2
- Managed node OS: Ubuntu Bionic (18.04)
