### ISSUE TITLE
Add user and group to service_list in vars main.yml

### ISSUE THREAD

**Issue by amacchiarella** [robertdebock/ansible-role-artifactory#8]
**Is your feature request related to a problem? Please describe.**
the main problem is that artifactory is always starting as root user

**Describe the solution you'd like**
Adding user_name and group_name in server_list will solve the problem
```
# Set the parameters required for the service.
service_list:
  - name: artifactory
    description: Start script for Artifactory
    start_command: "{{ artifactory_home }}/bin/artifactory.sh start"
    stop_command: "{{ artifactory_home }}/bin/artifactory.sh stop"
    type: forking
    status_pattern: artifactory
    user_name: "{{ artifactory_user }}"
    group_name: "{{ artifactory_group }}"

```
